"""Application configuration constants."""

# Nigerian states
NIGERIAN_STATES = [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", 
    "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "FCT", "Gombe", "Imo", 
    "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", 
    "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", 
    "Yobe", "Zamfara"
]

# Web scraping utilities
DEFAULT_HEADERS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0"
]

ECOM_PLATFORM_QUERIES = {
    "Shopify": ['site:myshopify.com', 'inurl:/products', 'shopify'],
    "WooCommerce": ['"WooCommerce" inurl:/product'],
    "Wix": ['site:wixsite.com OR "Powered by Wix"'],
    "BigCommerce": ['"BigCommerce" inurl:/products'],
    "Squarespace": ['"Powered by Squarespace" inurl:/shop'],
    "Magento": ['"Powered by Magento" OR inurl:/catalog/product'],
    "Etsy": ['site:etsy.com/shop'],
    "Amazon": ['site:amazon.com "Storefront" OR "Amazon Brand Store"']
}

PLATFORM_FINGERPRINTS = {
    "Shopify": [
        r"cdn\.shopify\.com", r"myshopify\.com", r"Shopify.theme",
        r'<meta[^>]+name=["\']shopify'
    ],
    "WooCommerce": [r"woocommerce", r"wp-content/plugins/woocommerce", r"wc-cart"],
    "Wix": [r"wixstatic\.com", r"X-Wix-Request-Id", r"X-Wix-Renderer-Server"],
    "BigCommerce": [r"bigcommerce", r"cdn\d?\.bigcommerce\.com"],
    "Squarespace": [r"squarespace\.com", r"sqs-layout", r"Static\.squarespace"],
    "Magento": [r"Magento", r"mage/cookies", r"mage-init", r"static/frontend/.+/Magento_"],
    "Etsy": [r"etsy\.com/shop", r"etsyassets\.com"],
    "Amazon": [r"amazon\.", r"amazon-adsystem\.com", r"SellerCentral"]
}

SOCIAL_PATTERNS = {
    "Instagram": r"(https?://(?:www\.)?instagram\.com/[A-Za-z0-9_.-]+/?(?:\?[^\"'\s<>]*)?)",
    "Facebook": r"(https?://(?:www\.)?facebook\.com/[A-Za-z0-9_.-]+/?(?:\?[^\"'\s<>]*)?)",
    "X/Twitter": r"(https?://(?:www\.)?(?:twitter\.com|x\.com)/[A-Za-z0-9_.-]+/?(?:\?[^\"'\s<>]*)?)",
    "TikTok": r"(https?://(?:www\.)?tiktok\.com/@[A-Za-z0-9_.-]+/?(?:\?[^\"'\s<>]*)?)",
    "YouTube": r"(https?://(?:www\.)?youtube\.com/(?:c/|channel/|@)[A-Za-z0-9_.-]+/?(?:\?[^\"'\s<>]*)?)",
}

WHATSAPP_LINK = r"(https?://(?:wa\.me|api\.whatsapp\.com)/[^\s\"'<>)]+)"
PHONE_REGEX = r"(?:(?:\+?\d{1,3})?[ -]?(?:\(?\d{2,4}\)?)[ -]?)?(?:\d[ -]?){6,14}\d"

# Themes
THEMES = {
    "Light": {
        "main_window": "#f5f5f5",
        "group_box": "#ffffff",
        "group_box_border": "#cccccc",
        "group_box_title": "#333333",
        "button": "#3498db",
        "button_hover": "#2980b9",
        "button_pressed": "#1a5276",
        "button_disabled": "#bdc3c7",
        "button_disabled_text": "#7f8c8d",
        "table": "#ffffff",
        "table_grid": "#dfe6e9",
        "table_border": "#bdc3c7",
        "table_selected": "#3498db",
        "table_selected_text": "#ffffff",
        "header": "#34495e",
        "header_text": "#ffffff",
        "header_border": "#2c3e50",
        "combobox": "#ffffff",
        "combobox_border": "#bdc3c7",
        "line_edit": "#ffffff",
        "line_edit_border": "#bdc3c7",
        "progress_bar": "#bdc3c7",
        "progress_bar_chunk": "#3498db",
        "toolbar": "#34495e",
        "toolbar_button": "transparent",
        "toolbar_button_text": "#ffffff",
        "toolbar_button_hover": "#2c3e50",
        "menubar": "#34495e",
        "menubar_text": "#ffffff",
        "menubar_selected": "#2c3e50",
        "menu": "#ffffff",
        "menu_border": "#bdc3c7",
        "menu_selected": "#3498db",
        "text_edit": "#ffffff",
        "text_edit_border": "#bdc3c7",
        "label": "#333333"
    },
    "Dark": {
        "main_window": "#2b2b2b",
        "group_box": "#3c3f41",
        "group_box_border": "#555555",
        "group_box_title": "#ffffff",
        "button": "#4e5a68",
        "button_hover": "#5a6675",
        "button_pressed": "#3e4651",
        "button_disabled": "#4a4a4a",
        "button_disabled_text": "#a0a0a0",
        "table": "#2d2d2d",
        "table_grid": "#404040",
        "table_border": "#555555",
        "table_selected": "#4e5a68",
        "table_selected_text": "#ffffff",
        "header": "#3c3f41",
        "header_text": "#ffffff",
        "header_border": "#555555",
        "combobox": "#3c3f41",
        "combobox_border": "#555555",
        "line_edit": "#3c3f41",
        "line_edit_border": "#555555",
        "progress_bar": "#555555",
        "progress_bar_chunk": "#4e5a68",
        "toolbar": "#3c3f41",
        "toolbar_button": "transparent",
        "toolbar_button_text": "#ffffff",
        "toolbar_button_hover": "#4e5a68",
        "menubar": "#3c3f41",
        "menubar_text": "#ffffff",
        "menubar_selected": "#4e5a68",
        "menu": "#3c3f41",
        "menu_border": "#555555",
        "menu_selected": "#4e5a68",
        "text_edit": "#3c3f41",
        "text_edit_border": "#555555",
        "label": "#ffffff"
    },
    "Blue": {
        "main_window": "#e6f2ff",
        "group_box": "#ffffff",
        "group_box_border": "#b3d9ff",
        "group_box_title": "#0066cc",
        "button": "#0066cc",
        "button_hover": "#0052a3",
        "button_pressed": "#004080",
        "button_disabled": "#b3d9ff",
        "button_disabled_text": "#66a3ff",
        "table": "#ffffff",
        "table_grid": "#d9edff",
        "table_border": "#b3d9ff",
        "table_selected": "#0066cc",
        "table_selected_text": "#ffffff",
        "header": "#0066cc",
        "header_text": "#ffffff",
        "header_border": "#0052a3",
        "combobox": "#ffffff",
        "combobox_border": "#b3d9ff",
        "line_edit": "#ffffff",
        "line_edit_border": "#b3d9ff",
        "progress_bar": "#b3d9ff",
        "progress_bar_chunk": "#0066cc",
        "toolbar": "#0066cc",
        "toolbar_button": "transparent",
        "toolbar_button_text": "#ffffff",
        "toolbar_button_hover": "#0052a3",
        "menubar": "#0066cc",
        "menubar_text": "#ffffff",
        "menubar_selected": "#0052a3",
        "menu": "#ffffff",
        "menu_border": "#b3d9ff",
        "menu_selected": "#0066cc",
        "text_edit": "#ffffff",
        "text_edit_border": "#b3d9ff",
        "label": "#0066cc"
    },
    "Green": {
        "main_window": "#e6ffe6",
        "group_box": "#ffffff",
        "group_box_border": "#b3ffb3",
        "group_box_title": "#009900",
        "button": "#009900",
        "button_hover": "#007a00",
        "button_pressed": "#006600",
        "button_disabled": "#b3ffb3",
        "button_disabled_text": "#66cc66",
        "table": "#ffffff",
        "table_grid": "#d9ffd9",
        "table_border": "#b3ffb3",
        "table_selected": "#009900",
        "table_selected_text": "#ffffff",
        "header": "#009900",
        "header_text": "#ffffff",
        "header_border": "#007a00",
        "combobox": "#ffffff",
        "combobox_border": "#b3ffb3",
        "line_edit": "#ffffff",
        "line_edit_border": "#b3ffb3",
        "progress_bar": "#b3ffb3",
        "progress_bar_chunk": "#009900",
        "toolbar": "#009900",
        "toolbar_button": "transparent",
        "toolbar_button_text": "#ffffff",
        "toolbar_button_hover": "#007a00",
        "menubar": "#009900",
        "menubar_text": "#ffffff",
        "menubar_selected": "#007a00",
        "menu": "#ffffff",
        "menu_border": "#b3ffb3",
        "menu_selected": "#009900",
        "text_edit": "#ffffff",
        "text_edit_border": "#b3ffb3",
        "label": "#009900"
    }
}